### ISSUE TITLE
Preview is not updating

### ISSUE THREAD

**Issue by Zettt** [lmtm/uncloak#3]
I have cloned and started the node server from the command line. The website starts, but changes in the right sidebar are not reflected in the preview on the left. What could be wrong here? 

Here's a console log from Chrome:

```
Font from origin 'http://public.slidesharecdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.slideshare.net' is therefore not allowed access.
127.0.0.1/:1 XMLHttpRequest cannot load http://localhost:8080/convert. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.
angular.js:12450 TypeError: Illegal invocation
    at angular.js:10258
    at processQueue (angular.js:14678)
    at angular.js:14694
    at Scope.$get.Scope.$eval (angular.js:15922)
    at Scope.$get.Scope.$digest (angular.js:15733)
    at Scope.$get.Scope.$apply (angular.js:16030)
    at done (angular.js:10545)
    at completeRequest (angular.js:10717)
    at XMLHttpRequest.requestError (angular.js:10668)
```

**Comment by Delapouite** [comment]
Hi

The first issue with public.slidesharecdn is not harmful, it's because the original reveal presentation contains an iframe on one of its slide.

As for the second one it seems that there's a mismatch between `localhost` and `127.0.0.1`

When you open your brower, on which one of these addresses do you connect? Did you try http://localhost:8080?
